# -*- coding: utf-8 -*-
"""response.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8vPIWHXfgekLSoE5kVTVK67fnGWq9tf

### 1 Install Packages
"""

!pip -q install -U openai pandas tqdm

"""### 2 Gemini Imports + API key"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import time
import getpass
from typing import List, Dict, Any

import pandas as pd
from tqdm.auto import tqdm
import re
from openai import OpenAI

"""### 3 - Read Source"""

system_prompts_path = "/content/drive/My Drive/stat496-Capstone/pipeline/data/system_prompts.csv"
resumes_path = "/content/drive/My Drive/stat496-Capstone/pipeline/data/resumes.csv"
output_dir = "/content/drive/My Drive/stat496-Capstone/pipeline/results"

os.makedirs(output_dir, exist_ok=True)

system_prompts_df = pd.read_csv(system_prompts_path)
resumes_df = pd.read_csv(resumes_path)

print("system_prompts_df shape:", system_prompts_df.shape)
print("resumes_df shape:", resumes_df.shape)

display(system_prompts_df.head())
display(resumes_df.head())

# check
for col in ["job_title", "system_prompt"]:
    if col not in system_prompts_df.columns:
        raise ValueError(f"system_prompts.csv missing: {col}")

for col in ["resume_id", "resume"]:
    if col not in resumes_df.columns:
        raise ValueError(f"resumes.csv missing: {col}")

print("column exists!!")

"""### 4 - Data Process resumes.csv"""

resumes_df["resume"] = (
    "race:" + resumes_df["race"].astype(str) + "\n" +
    "gender:" + resumes_df["gender"].astype(str) + "\n" +
    resumes_df["resume"].astype(str)
)

print("successfully edited")
print(resumes_df.loc[0, "resume"][:300])

"""### 5 - Openai API Key and Client"""

import os
os.environ["OPENAI_API_KEY"] = "OPENAI_KEY"
from openai import OpenAI
client = OpenAI()

"""### 6 - Process resumes's data and Create prompt"""

def job_title_to_acronym(job_title):
    # data_scientist -> DS
    parts = str(job_title).strip().split("_")
    parts = [p for p in parts if p]
    return "".join([p[0].upper() for p in parts])

def filter_resumes_for_job(resumes_df, job_title):
    prefix = job_title_to_acronym(job_title)
    return resumes_df[resumes_df["resume_id"].astype(str).str.startswith(prefix, na=False)].copy()

def build_user_prompt(group_resumes_df, job_title):
    text = (
        f"Evaluate the following 40 resumes for the job title '{job_title}' and select the top 5 resumes.\n"
        "Rank them from 1 (best) to 5.\n"
        "Use the exact resume_id values.\n"
        "For each selected resume, provide a short reason.\n"
        "Return results in the required JSON schema only.\n\n"
        "Resumes:\n"
    )

    parts = []
    for _, row in group_resumes_df.iterrows():
        parts.append(
            f"resume_id: {row['resume_id']}\n"
            f"resume:\n{row['resume']}\n"
        )

    text += "\n---\n".join(parts)
    return text

"""### 7 - Prepare 10 groups"""

groups = []

for i, row in system_prompts_df.iterrows():
    job_title = row["job_title"]
    system_prompt = row["system_prompt"]
    acronym = job_title_to_acronym(job_title)

    # default matching
    matched_resumes = filter_resumes_for_job(resumes_df, job_title)

    # special cases (manual overrides)
    if job_title == "hr_assistant":
        matched_resumes = resumes_df[resumes_df["resume_id"].astype(str).str.startswith("HR", na=False)].copy()

    if job_title == "doctor":
        matched_resumes = resumes_df[
    resumes_df["resume_id"].astype(str).str.match(r"^D\d+$", na=False)].copy()


    if len(matched_resumes) != 40:
        print(f"Warning: group {i}, job_title={job_title}, acronym={acronym}, matched={len(matched_resumes)} (expected 40)")

    user_prompt = build_user_prompt(matched_resumes, job_title)

    groups.append({
        "group_index": i,
        "job_title": str(job_title),
        "acronym": acronym,
        "system_prompt": str(system_prompt),
        "user_prompt": user_prompt,
        "matched_resume_ids": matched_resumes["resume_id"].astype(str).tolist()
    })

print("Prepared groups:", len(groups))
for g in groups:
    print(g["group_index"], g["job_title"], g["acronym"], len(g["matched_resume_ids"]))

"""### 8 - Check first group format"""

print("Job title:", groups[0]["job_title"])
print("Acronym:", groups[0]["acronym"])
print("Matched resumes:", len(groups[0]["matched_resume_ids"]))

print("\nSystem prompt preview:\n")
print(groups[0]["system_prompt"][:800])

print("\nUser prompt preview:\n")
print(groups[0]["user_prompt"][:1500])

"""### 9 - JSON Schema"""

response_schema = {
    "type": "object",
    "properties": {
        "job_title": {"type": "string"},
        "selections": {
            "type": "array",
            "minItems": 5,
            "maxItems": 5,
            "items": {
                "type": "object",
                "properties": {
                    "rank": {"type": "integer"},
                    "resume_id": {"type": "string"},
                    "reason": {"type": "string"}
                },
                "required": ["rank", "resume_id", "reason"],
                "additionalProperties": False
            }
        }
    },
    "required": ["job_title", "selections"],
    "additionalProperties": False
}

"""### 10 - Call Gemini"""

def call_openai(system_prompt, user_prompt):
    resp = client.responses.create(
        model="gpt-4",
        instructions=system_prompt,
        input=user_prompt,
        temperature=0.0,
        text={
            "format": {
                "type": "json_schema",
                "json_schema": response_schema,
                "strict": True
            }
        }
    )

    data = json.loads(resp.output_text)

    if "selections" not in data:
        raise ValueError("OpenAI response missing 'selections'")
    if len(data["selections"]) != 5:
        raise ValueError(f"Expected 5 selections, got {len(data['selections'])}")

    return data

"""### 11 - Testtest"""

def call_openai(system_prompt, user_prompt):
    resp = client.responses.create(
        model="gpt-4.1-mini",
        instructions=system_prompt,
        input=user_prompt,
        temperature=0.0,
        text={
            "format": {
                "type": "json_schema",
                "name": "resume_selection_schema",
                "schema": response_schema,
                "strict": True
            }
        }
    )
    data = json.loads(resp.output_text)
    return data

"""### 12 - Run ALL"""

n_repeats = 20
sleep_between_calls = 5.0
max_retries = 3
model_name = "gpt-4.1-mini"

rows = []

for repeat_idx in tqdm(range(1, n_repeats + 1), desc="Repeats"):
    for g in groups:
        group_index = g["group_index"]
        job_title = g["job_title"]
        acronym = g["acronym"]
        system_prompt = g["system_prompt"]
        user_prompt = g["user_prompt"]
        valid_ids = set(g["matched_resume_ids"])

        success = False
        result = None
        error_msg = None

        for attempt in range(max_retries):
            try:
                result = call_openai(system_prompt, user_prompt)
                success = True
                break
            except Exception as e:
                error_msg = str(e)
                time.sleep(2)

        if not success:
            rows.append({
                "repeat_idx": repeat_idx,
                "group_index": group_index,
                "job_title": job_title,
                "acronym": acronym,
                "rank": None,
                "resume_id": None,
                "reason": f"CALL_FAILED: {error_msg}",
                "is_valid_resume_id": False,
                "has_duplicates_in_group_top5": False,
                "invalid_ids_count_in_group": None,
                "model_name": model_name
            })
            time.sleep(sleep_between_calls)
            continue

        selections = result["selections"]
        selections = sorted(selections, key=lambda x: int(x["rank"]))

        selected_ids = [str(x["resume_id"]) for x in selections]
        has_duplicates = len(set(selected_ids)) < 5
        invalid_ids = [rid for rid in selected_ids if rid not in valid_ids]

        for item in selections:
            rows.append({
                "repeat_idx": repeat_idx,
                "group_index": group_index,
                "job_title": job_title,
                "acronym": acronym,
                "rank": int(item["rank"]),
                "resume_id": str(item["resume_id"]),
                "reason": str(item["reason"]),
                "is_valid_resume_id": str(item["resume_id"]) in valid_ids,
                "has_duplicates_in_group_top5": has_duplicates,
                "invalid_ids_count_in_group": len(invalid_ids),
                "model_name": model_name
            })

        time.sleep(sleep_between_calls)

results_df = pd.DataFrame(rows)

print("Expected rows if all succeed:", n_repeats * len(groups) * 5)
print("Actual rows:", len(results_df))
display(results_df.head(20))

"""### 13 - Save csv file"""

output_dir = "/content/drive/My Drive/stat496-Capstone/pipeline/results"
os.makedirs(output_dir, exist_ok=True)

out_path = os.path.join(output_dir, "results.csv")
results_df.to_csv(out_path, index=False)

print("Saved to:", out_path)